### PR TITLE
vue3-openlayers is added

### PR DESCRIPTION
**Pull request by MelihAltintas**

### CODE REVIEW

**Comment by Jogai** [comment]
Looks awesome to me!

**Comment by MelihAltintas** [comment]
Thanks @Jogai :)

**Comment by vuesomedev** [comment]
pls update

**Comment by MelihAltintas** [comment]
@vuesomedev solved

**Comment by Jogai** [comment]
Do you even git bro?

But seriously. Why not merge the PR's? That's how all awesome list do it, and git works in general.

**Comment by vuesomedev** [comment]
I know how git works, but for 20 conflicting prs i've decided to do it this way as it saved me time.

**Comment by Jogai** [comment]
Yeah, it was a joke obviously, but If you need help maintaining this repo I can help (since good jokes usually have some truth in them ;). I usually look at the new PR's anyway that will save you time, and I think if PR's are reviewed within a reasonable time it's easier to keep up.

**Comment by vuesomedev** [comment]
Aggree the problem was I totally checked out for a couple of months. Now I want keep it up to date, but whenever I see myself slipping again I'll contact you. Thanks

**Pull request closed without merging**
